var mongoose=require("mongoose")
var userSchema=new mongoose.Schema({
    username:{
        type:String,
        unique:true,
        required:true
    },
    employee_id:{
        type:String,
        unique:true,
        required:true,
    },
    role:{
        type:String,
        unique:true,
        required:true,
        enum:["manager","accountant","ceo","pharmacist"]
    },
    pass_hash:{
        type:String,
        //required:true
    },
    email:{
        type:String,
        required:true
    },
    fname:{
        type:String,
        required:true
    },
    lname:{
        type:String,
        required:true
    },
    mname:{
        type:String,
    },
    isEmailVer:{
        type:Boolean,
        default:false
    }
})
var User=mongoose.model("User",userSchema)
module.exports=User;